# Generated by Django 5.2.8 on 2025-11-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('serialNo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=30)),
                ('productId', models.CharField(max_length=16)),
                ('ManufactureDate', models.CharField(max_length=15)),
                ('deliverycharge', models.CharField(max_length=15)),
                ('expiredate', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=15)),
            ],
        ),
    ]
